const express=require("express"),router=express.Router();
const config=require("../../config"),db=require("../db"),hz=require("../haozhuma");
router.post("/card/verify",(req,res)=>{const card=db.validateCard(req.body.card||"");if(!card)return res.json({ok:false,msg:"卡密不存在"});if(card.status==="completed"){const o=db.getCompletedOrder(card.card_code);return res.json({ok:true,status:"completed",sms:o?o.sms_code:null,phone:o?o.phone:card.phone})}if(card.status==="used"){const o=db.getActiveOrder(card.card_code);if(o)return res.json({ok:true,status:"active",phone:card.phone,order_id:card.order_id});return res.json({ok:true,status:"already_used",phone:card.phone})}res.json({ok:true,status:"unused"})});
router.post("/card/getphone",async(req,res)=>{const code=(req.body.card||"").toUpperCase().trim();const card=db.validateCard(code);if(!card)return res.json({ok:false,msg:"卡密不存在"});if(card.status==="used"){const o=db.getActiveOrder(code);if(o)return res.json({ok:true,phone:card.phone,order_id:card.order_id});return res.json({ok:false,msg:"卡密已使用且无活跃订单"})}try{const r=await hz.getPhone();if(!r||!r.phone)return res.json({ok:false,msg:"取号失败"});db.markCardUsed(code,r.phone,r.orderId,config.haozhuma.itemId);res.json({ok:true,phone:r.phone,order_id:r.orderId})}catch(e){res.json({ok:false,msg:"取号失败: "+e.message})}});router.get("/card/sms",async(req,res)=>{const code=(req.query.card||"").toUpperCase().trim();const card=db.validateCard(code);if(!card)return res.json({ok:false,msg:"卡密不存在"});if(card.status==="completed"||card.status==="used"){const o=db.getCompletedOrder(code)||db.getActiveOrder(code);if(o&&o.sms_code)return res.json({ok:true,pending:false,sms:o.sms_code})}if(card.status!=="used")return res.json({ok:false,msg:"卡密未取号或已过期"});try{const r=await hz.getSms(card.order_id,card.phone);if(r.pending)return res.json({ok:true,pending:true,sms:null});if(r.sms!==undefined){db.markOrderSmsReceived(code,r.sms);res.json({ok:true,pending:false,sms:r.sms})}else res.json({ok:false,msg:r.msg||"获取验证码失败"})}catch(e){res.json({ok:false,msg:"查询失败: "+e.message})}});
router.post("/card/release",async(req,res)=>{const code=(req.body.card||"").toUpperCase().trim();const card=db.validateCard(code);if(!card)return res.json({ok:false,msg:"卡密不存在"});if(db.hasCompletedOrder(code))return res.json({ok:false,msg:"卡密已完成，不可释放"});if(card.status==="used"&&card.order_id){try{await hz.releasePhone(card.order_id,card.phone)}catch(e){}}db.markCardReleased(code);res.json({ok:true})});
// ========== Account mode (账号库验证模式，取代卡密) ==========
router.post("/account/verify",(req,res)=>{const phone=String(req.body.phone||"").trim();if(!/^1\d{10}$/.test(phone))return res.json({ok:false,msg:"请输入正确的11位手机号账号"});const acc=db.getAccount(phone);if(!acc)return res.json({ok:false,msg:"账号未录入，请联系管理员"});if(acc.status==="used")return res.json({ok:true,status:"used",phone:acc.phone,sms:acc.sms_code});if(acc.status==="active")return res.json({ok:true,status:"active",phone:acc.phone});res.json({ok:true,status:"unused",phone:acc.phone})});
router.get("/account/sms",async(req,res)=>{const phone=String(req.query.phone||"").trim();if(!/^1\d{10}$/.test(phone))return res.json({ok:false,msg:"参数错误"});const acc=db.getAccount(phone);if(!acc)return res.json({ok:false,msg:"账号未录入"});if(acc.status==="used"&&acc.sms_code)return res.json({ok:true,pending:false,sms:acc.sms_code});if(acc.status==="unused")db.markAccountActive(phone);try{const r=await hz.getSms(acc.order_id,phone);if(r.pending)return res.json({ok:true,pending:true,sms:null});if(r.sms!==undefined){db.markAccountUsed(phone,r.sms);return res.json({ok:true,pending:false,sms:r.sms})}// 不是pending也没拿到明确的短信内容 → 视为"还没到"，继续轮询（避免手动录入号因非豪猪订单被误判为失败中断轮询）
  return res.json({ok:true,pending:true,sms:null})}catch(e){return res.json({ok:true,pending:true,sms:null})}});
router.post("/account/release",(req,res)=>{const phone=String(req.body.phone||"").trim();const acc=db.getAccount(phone);if(!acc)return res.json({ok:false,msg:"账号未录入"});if(acc.status==="used")return res.json({ok:false,msg:"账号已使用"});db.markAccountReleased(phone);res.json({ok:true})});
module.exports=router;
